version: '3'
services:
  app:
    build:
      context: docker/app
      args: 
        version: '1.10'
    env_file: .env
    restart: always
    command: '/start.sh'
    working_dir: '/go/src/app'
    volumes:
      - './go/src/app:/go/src/app'