#!/bin/bash

curl -L -o goenv.tar.gz https://github.com/toretto460/goenv/archive/0.1.tar.gz

mkdir goenv && tar xzvf goenv.tar.gz -C goenv --strip-components 1 && rm -f goenv.tar.gz

echo "entering into goenv $(pwd)/goenv"
cd goenv