#!/bin/bash

curl -L -o goenv.tar.gz https://github.com/toretto460/goenv/archive/0.1.6.tar.gz

mkdir goenv && tar xzvf goenv.tar.gz -C goenv --strip-components 1 && rm -f goenv.tar.gz

# Initialize the container
cd goenv
bin/init.sh

echo "Your env is ready at $(pwd)"
cat install/banner && rm -Rf install
echo "Let's start creating your app"